### ISSUE TITLE
Verifiers  roadmap

### ISSUE THREAD

**Issue by rmed** [guluc3m/gul-gultalks#14]
- [X] Generate Verifier when creating a new event
- [X] Generate Verifier when voting
- [X] Mark Events as _active_ if it has been verified and as _inactive_ when first created through the wizard
- [x] Generate URL in mail with form `gultalks_host/verify?token=TOKEN`
- [X] Activate the event and mark the verifier as _verified_ when verifying an event
- [X] Update vote count and mark the verifier as _verified_ when verifying a vote
- [X] Add error view when trying to verify an invalid URL
- [X] Only show _shown_ Events in list
- [x] Only send token in mail
